# Global values that tailor this chart for a given service

nameOverride: ""   # Optionally override release name
fullnameOverride: ""

image:
  repository: ghcr.io/plasma-engine/service
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  hosts: []   # e.g., [ { host: api.dev.example.com, paths: [/] } ]
  tls: []     # e.g., [ { hosts: [api.dev.example.com], secretName: tls-secret } ]

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

env:
  # Key-value pairs to inject as environment variables
  # example:
  # - name: LOG_LEVEL
  #   value: info
  # - name: OTEL_EXPORTER_OTLP_ENDPOINT
  #   value: http://otel-collector.observability:4317
  - name: PLACEHOLDER
    value: "set-me"

livenessProbe:
  enabled: true
  path: /health
  port: 8080

readinessProbe:
  enabled: true
  path: /ready
  port: 8080

podAnnotations: {}
podLabels: {}

nodeSelector: {}
affinity: {}
tolerations: []

