name: reusable-lint-test-python

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: '3.11'
    secrets: {}

jobs:
  lint-test:
    name: Lint and Test (Python)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install ruff black pytest
      - name: Lint (ruff)
        run: ruff check .
      - name: Format (black --check)
        run: black --check .
      - name: Test (pytest)
        run: pytest -q
      - name: Artifacts: test results (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: python-test-artifacts
          path: |
            .pytest_cache
            **/coverage*
        retention-days: 7

