# Placeholder Exa OpenAPI (YAML). Replace via Rube MCP authoritative spec.
openapi: 3.0.3
info:
  title: Exa API
  version: 0.0.0-placeholder
paths:
  /v1/search:
    get:
      summary: Search documents
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
