#
# Explainer: Template workflow for JS/TS lint. Not active until copied to .github/workflows/.
# TODO(devx@plasma): Pick a single package manager (pnpm/npm/yarn) and cache strategy.

name: js-quality
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**/*.js'
      - '**/*.ts'
      - '**/*.tsx'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install eslint (project-local if package.json present)
        run: |
          if [ -f package.json ]; then
            npm ci --no-audit --no-fund || npm install --no-audit --no-fund
          else
            npm install --global eslint
          fi
      - name: ESLint
        run: |
          if [ -f package.json ]; then
            npx --yes eslint . || true # TODO: tighten to fail on error
          else
            eslint . || true
          fi

