name: cursor-agent-dispatch

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      pr_number:
        description: "Pull request number to classify"
        required: false

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Resolve pull request number
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          if [ -z "$PR_NUMBER" ]; then
            PR_NUMBER="${{ inputs.pr_number }}"
          fi
          if [ -z "$PR_NUMBER" ]; then
            echo "PR number is required (provide via workflow_dispatch input)" >&2
            exit 1
          fi
          echo "INPUT_PR_NUMBER=$PR_NUMBER" >> "$GITHUB_ENV"

      - name: Run Cursor dispatch automation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          CURSOR_AGENT_CLASSIFIERS: ${{ vars.CURSOR_AGENT_CLASSIFIERS }}
        run: |
          echo "Dispatching specialized Cursor agents"
          python scripts/automation/cursor_dispatch.py

