# Explainer: Reusable Python CI workflow for Plasma Engine repos.
# Purpose: Lint (ruff/black), test (pytest), and report coverage.
# Inputs: python-version, working-directory
# Outputs: junit.xml and coverage.xml artifacts
# Links: docs/devops/playbooks/ci-cd.md

name: python-ci

on:
  workflow_call:
    inputs:
      python-version:
        description: Python version to use
        required: false
        type: string
        default: '3.11'
      working-directory:
        description: Directory to run commands in
        required: false
        type: string
        default: '.'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        working-directory: ${{ inputs.working-directory }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install -r requirements-dev.txt || true
          pip install ruff black pytest pytest-cov
        # Purpose: Ensure base and dev deps present; add lint/test deps

      - name: Lint (ruff)
        working-directory: ${{ inputs.working-directory }}
        run: ruff check .
        # Output: exit code and printed issues

      - name: Format check (black)
        working-directory: ${{ inputs.working-directory }}
        run: black --check .

      - name: Run tests (pytest)
        working-directory: ${{ inputs.working-directory }}
        run: pytest -q --junitxml=junit.xml --cov=. --cov-report=xml

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-ci-artifacts
          path: |
            ${{ inputs.working-directory }}/junit.xml
            ${{ inputs.working-directory }}/coverage.xml

