 # Reusable workflow: build
 # Purpose: Build artifacts for services (Python/Node) and validate basic formatting
 # Inputs/outputs: none currently; extend per service
 # Links: docs/devops/playbooks/build.md
 name: reusable-build
 on:
   workflow_call:
     inputs: {}
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
           node-version: '22'
       - name: Setup Python
         uses: actions/setup-python@v5
         with:
           python-version: '3.13'
       - name: Install tooling (npm)
         run: |
           npm i -g npm@latest
       - name: Install tooling (pip)
         run: |
           python -m pip install --upgrade pip
           pip install black ruff
       - name: Format check (black)
         run: |
           black --check . || true # TODO: tighten to fail later
       - name: Lint check (ruff)
         run: |
           ruff check . || true # TODO: tighten to fail later
