 name: reusable-deploy
 on:
   workflow_call:
     inputs:
       environment:
         required: true
         type: string
       service:
         required: false
         type: string
 jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - name: Deploy
         uses: ./.github/../ci/actions/deploy
         with:
           environment: ${{ inputs.environment }}
           service: ${{ inputs.service }}
