name: IaC - Terraform Validate and Plan

# This workflow validates Terraform and optionally runs a plan for PRs.
# TODO: Configure remote state backend and cloud credentials via GitHub Environments.

on:
  pull_request:
    paths:
      - 'plasma-engine-infra/**'
      - '.github/workflows/terraform.yml'
  workflow_dispatch: {}

jobs:
  terraform:
    name: Terraform Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Format
        working-directory: plasma-engine-infra/infra/terraform
        run: terraform fmt -recursive -check || true
        # Purpose: enforce canonical formatting (soft-fail initially)

      - name: Validate (envs/dev)
        working-directory: plasma-engine-infra/infra/terraform/envs/dev
        run: |
          terraform init -backend=false
          terraform validate || true
        # Purpose: ensure syntax and provider blocks parse correctly
        # Inputs: *.tf files

      - name: Plan (envs/dev) - dry run
        if: github.event_name == 'pull_request'
        env:
          TF_VAR_environment: dev
        working-directory: plasma-engine-infra/infra/terraform/envs/dev
        run: |
          terraform init -backend=false
          terraform plan -lock=false -input=false || true
        # Purpose: produce a speculative plan; backend disabled for forks

